"""t_af0935a6 — is this IP a *verified* search/AI crawler?

30 of the 38 ``installed:stranger`` rows on 2026-10-10 were anonymous installs
from crawler address space: 24 from Baidu's spider (116.179.x, which is China
Unicom ISP space, so it is not hosting and ``hosting_networks`` cannot see it).
The funnel ledger's ``classify`` uses :func:`crawler_network` to downgrade an
IP-only subject (no email, no key) to ``unknown`` with the vendor and the
proof source named in the evidence string. A subject with an email or a key is
never downgraded by this rule.

Admission rule for ``config/crawler_networks.txt`` (never hide a real
stranger, never list an ISP block):

* vendors that PUBLISH their crawler ranges contribute exactly those
  prefixes, labelled ``<vendor>:<source-url>``;
* vendors that publish no list (Baidu) contribute exact /32 or /128 entries
  only, each one proven by forward-confirmed reverse DNS, labelled
  ``<vendor>:fcrdns:<ptr-hostname>:<date>``.

The file is generated by ``scripts/refresh_crawler_networks.py``; that script
is the only place network calls happen. Lookup here is the same bisect as
``hosting_networks``: O(log n), no I/O beyond reading the file once, and a
missing or corrupt file degrades to "not a crawler", never an error.
"""

from __future__ import annotations

import bisect
import ipaddress
import logging
from functools import lru_cache
from pathlib import Path

from app.services.hosting_networks import _flatten

logger = logging.getLogger(__name__)

DATA_PATH = Path(__file__).resolve().parent.parent.parent / "config" / "crawler_networks.txt"


@lru_cache(maxsize=4)
def _load(path_str: str) -> dict[int, tuple[list[int], list[int], list[str]]]:
    """Per IP version: (sorted starts, matching ends, labels), non-overlapping."""
    rows: dict[int, list[tuple[int, int, str]]] = {4: [], 6: []}
    path = Path(path_str)
    try:
        text = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        logger.warning("crawler_networks: %s missing; no IP is treated as a crawler", path)
        text = ""
    except (OSError, UnicodeDecodeError) as exc:
        logger.warning("crawler_networks: %s unreadable (%s); no IP is treated as a crawler", path, exc)
        text = ""
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        cidr, _, label = line.partition(" ")
        try:
            net = ipaddress.ip_network(cidr, strict=False)
        except ValueError:
            continue
        rows[net.version].append(
            (int(net.network_address), int(net.broadcast_address), label.strip() or "crawler")
        )
    out = {}
    for version, items in rows.items():
        segments = _flatten(items)
        out[version] = (
            [s for s, _, _ in segments],
            [e for _, e, _ in segments],
            [lbl for _, _, lbl in segments],
        )
    return out


def crawler_network(ip: str | None, *, path: Path | None = None) -> tuple[str, str] | None:
    """Return ``(vendor, source)`` if *ip* is a verified crawler address, else None.

    The label ``Baidu:fcrdns:host.crawl.baidu.com:2026-10-10`` splits at the
    first colon into vendor ``Baidu`` and source ``fcrdns:host...:2026-10-10``.
    """
    if not ip:
        return None
    try:
        addr = ipaddress.ip_address(ip.strip())
    except ValueError:
        return None
    if isinstance(addr, ipaddress.IPv6Address) and addr.ipv4_mapped is not None:
        addr = addr.ipv4_mapped
    starts, ends, labels = _load(str(path or DATA_PATH))[addr.version]
    value = int(addr)
    i = bisect.bisect_right(starts, value) - 1
    if i >= 0 and value <= ends[i]:
        vendor, _, source = labels[i].partition(":")
        return vendor or "crawler", source or "unspecified"
    return None


def clear_cache() -> None:
    """Test hook."""
    _load.cache_clear()
