"""pricing0928 (t_7f5808d2, E1) — is this IP in a cloud-hosting network?

90 of 93 "stranger" installs over 30 days came from AWS, Microsoft and Hetzner
address space. That traffic is agent sandboxes, catalog crawlers and our own
cold-start harness running in the cloud, not a person. Counting it as
``stranger`` made every conversion rate look like a product failure.

The funnel ledger's ``classify`` uses :func:`hosting_network` to downgrade an
IP-only subject from these networks to ``unknown``, with the provider named in
the evidence string, so the row stays auditable.

Data: ``config/hosting_networks.txt``, one ``<cidr> <label>`` per line,
generated by ``scripts/refresh_hosting_networks.py`` from RIPEstat. Lookup is a
bisect over sorted integer ranges: O(log n), no network calls, and a missing or
corrupt file degrades to "not hosting" (the pre-fix behaviour), never an error.
"""

from __future__ import annotations

import bisect
import ipaddress
import logging
from functools import lru_cache
from pathlib import Path

logger = logging.getLogger(__name__)

DATA_PATH = Path(__file__).resolve().parent.parent.parent / "config" / "hosting_networks.txt"


@lru_cache(maxsize=4)
def _load(path_str: str) -> dict[int, tuple[list[int], list[int], list[str]]]:
    """Per IP version: (sorted starts, matching ends, labels). Non-overlapping."""
    rows: dict[int, list[tuple[int, int, str]]] = {4: [], 6: []}
    path = Path(path_str)
    if not path.exists():
        logger.warning("hosting_networks: %s missing; no IP is treated as hosting", path)
    else:
        for raw in path.read_text(encoding="utf-8").splitlines():
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            cidr, _, label = line.partition(" ")
            try:
                net = ipaddress.ip_network(cidr, strict=False)
            except ValueError:
                continue
            rows[net.version].append(
                (int(net.network_address), int(net.broadcast_address), label.strip() or "hosting")
            )
    out = {}
    for version, items in rows.items():
        items.sort()
        out[version] = ([s for s, _, _ in items], [e for _, e, _ in items], [lbl for _, _, lbl in items])
    return out


def hosting_network(ip: str | None, *, path: Path | None = None) -> str | None:
    """Return the provider label (e.g. ``"AWS"``) if *ip* is hosting space, else None."""
    if not ip:
        return None
    try:
        addr = ipaddress.ip_address(ip.strip())
    except ValueError:
        return None
    starts, ends, labels = _load(str(path or DATA_PATH))[addr.version]
    value = int(addr)
    i = bisect.bisect_right(starts, value) - 1
    if i >= 0 and value <= ends[i]:
        return labels[i]
    return None


def clear_cache() -> None:
    """Test hook."""
    _load.cache_clear()
