"""pricing0928 (t_7f5808d2, E1) — is this IP in a cloud-hosting network?

90 of 93 "stranger" installs over 30 days came from AWS, Microsoft and Hetzner
address space. That traffic is agent sandboxes, catalog crawlers and our own
cold-start harness running in the cloud, not a person. Counting it as
``stranger`` made every conversion rate look like a product failure.

The funnel ledger's ``classify`` uses :func:`hosting_network` to downgrade an
IP-only subject from these networks to ``unknown``, with the provider named in
the evidence string, so the row stays auditable.

Data: ``config/hosting_networks.txt``, one ``<cidr> <label>`` per line,
generated by ``scripts/refresh_hosting_networks.py`` from RIPEstat. Lookup is a
bisect over sorted integer ranges: O(log n), no network calls, and a missing or
corrupt file degrades to "not hosting" (the pre-fix behaviour), never an error.
"""

from __future__ import annotations

import bisect
import ipaddress
import logging
from functools import lru_cache
from pathlib import Path

logger = logging.getLogger(__name__)

DATA_PATH = Path(__file__).resolve().parent.parent.parent / "config" / "hosting_networks.txt"


@lru_cache(maxsize=4)
def _load(path_str: str) -> dict[int, tuple[list[int], list[int], list[str]]]:
    """Per IP version: (sorted starts, matching ends, labels), non-overlapping."""
    rows: dict[int, list[tuple[int, int, str]]] = {4: [], 6: []}
    path = Path(path_str)
    if not path.exists():
        logger.warning("hosting_networks: %s missing; no IP is treated as hosting", path)
    else:
        for raw in path.read_text(encoding="utf-8").splitlines():
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            cidr, _, label = line.partition(" ")
            try:
                net = ipaddress.ip_network(cidr, strict=False)
            except ValueError:
                continue
            rows[net.version].append(
                (int(net.network_address), int(net.broadcast_address), label.strip() or "hosting")
            )
    out = {}
    for version, items in rows.items():
        segments = _flatten(items)
        out[version] = (
            [s for s, _, _ in segments],
            [e for _, e, _ in segments],
            [lbl for _, _, lbl in segments],
        )
    return out


def _flatten(items: list[tuple[int, int, str]]) -> list[tuple[int, int, str]]:
    """Split nested ranges into disjoint segments; the most specific label wins.

    The refresh script collapses prefixes per label only, so a range under one
    label can sit inside a range under another (``172.217.0.0/16 Google``
    around ``172.217.56.0/21 GoogleCloud``). A bisect over the raw rows lands
    on the inner range and misses every address past its end. CIDR blocks are
    always nested or disjoint, so one sweep with a stack of open ranges yields
    segments that cover exactly the union of the input.
    """
    segments: list[tuple[int, int, str]] = []
    stack: list[tuple[int, str]] = []  # (end, label) of open ranges, outermost first
    cursor = 0

    def close_until(limit: int) -> None:
        nonlocal cursor
        while stack and stack[-1][0] < limit:
            end, label = stack.pop()
            if cursor <= end:
                segments.append((cursor, end, label))
                cursor = end + 1

    for start, end, label in sorted(items, key=lambda r: (r[0], -r[1], r[2])):
        close_until(start)
        if stack and cursor < start:
            segments.append((cursor, start - 1, stack[-1][1]))
        cursor = start
        stack.append((end, label))
    close_until(1 << 128)
    return segments


def hosting_network(ip: str | None, *, path: Path | None = None) -> str | None:
    """Return the provider label (e.g. ``"AWS"``) if *ip* is hosting space, else None."""
    if not ip:
        return None
    try:
        addr = ipaddress.ip_address(ip.strip())
    except ValueError:
        return None
    starts, ends, labels = _load(str(path or DATA_PATH))[addr.version]
    value = int(addr)
    i = bisect.bisect_right(starts, value) - 1
    if i >= 0 and value <= ends[i]:
        return labels[i]
    return None


def clear_cache() -> None:
    """Test hook."""
    _load.cache_clear()
