#!/usr/bin/env bash
# scripts/open_skill_sync_pr.sh
# Called from .github/workflows/sync-recipes-skill.yml after the sync script
# has copied artifacts. Detects diff, commits, pushes branch, opens PR.
#
# Required env vars:
#   SOURCE_SHA         — recipes-api commit SHA that triggered this sync
#   SOURCE_AUTHOR      — github.actor from the trigger event
#   SOURCE_REPO        — github.repository (e.g. wisechef-ai/recipes-api)
#   SOURCE_COMMIT_MSG  — github.event.head_commit.message
#   SKILL_REPO_DIR     — local path to checked-out recipes-skill
#   GH_TOKEN           — PAT with repo scope on wisechef-ai/recipes-skill
#   FORCE_PR           — "true" to open PR even when there's no diff
set -euo pipefail

cd "$SKILL_REPO_DIR"

if [ -z "$(git status --porcelain)" ] && [ "${FORCE_PR:-false}" != "true" ]; then
  echo "no_changes=true" >> "$GITHUB_OUTPUT"
  echo "No changes to sync."
  exit 0
fi

echo "no_changes=false" >> "$GITHUB_OUTPUT"
git status --short

SHA_SHORT=$(echo "$SOURCE_SHA" | cut -c1-7)
BRANCH="auto/sync-from-recipes-api-${SHA_SHORT}"
git checkout -b "$BRANCH"
git add -A
git commit -m "auto-sync: mirror artifacts from ${SOURCE_REPO}@${SHA_SHORT}

Source commit: ${SOURCE_SHA}
Source author: ${SOURCE_AUTHOR}
Source repo:   ${SOURCE_REPO}

This commit is auto-generated by sync-recipes-skill.yml. Edit upstream and the
bot will sync; do not edit mirrored files here directly."
git push -u origin "$BRANCH"

# Build PR body in a temp file (heredoc inside YAML run: blocks crashes the parser
# per manual-deploy-to-github-actions-pipeline pitfall #9 — that's why this lives
# in a shell script, not directly in the workflow YAML).
BODY_FILE=$(mktemp)
{
  echo "Auto-generated mirror PR from \`${SOURCE_REPO}@${SOURCE_SHA}\`."
  echo
  echo "**What this PR contains:**"
  echo "- Updated MCP tool reference (if \`app/mcp/server.py\` changed)"
  echo "- Updated CLI binary (if \`tools/recipes_cli.py\` changed)"
  echo "- Updated docs (if \`docs/recipes-skill/\` changed)"
  echo
  echo "**Source commit message:**"
  echo
  echo "\`\`\`"
  echo "$SOURCE_COMMIT_MSG"
  echo "\`\`\`"
  echo
  echo "**Reviewer guidance:**"
  echo "1. Verify the diff matches what the upstream commit intended"
  echo "2. Run \`scripts/install-test.sh\` if tools/cli changed"
  echo "3. Merge when green"
  echo
  echo "cc @${SOURCE_AUTHOR}"
} > "$BODY_FILE"

gh pr create \
  --title "auto-sync from recipes-api@${SHA_SHORT}" \
  --body-file "$BODY_FILE"

rm -f "$BODY_FILE"
