#!/usr/bin/env python3
"""scripts/refresh_hosting_networks.py — regenerate config/hosting_networks.txt.

pricing0928 (t_7f5808d2, E1): 90 of 93 "stranger" installs in 30 days came from
cloud-hosting ASNs (AWS, Microsoft, Hetzner). Those are agent sandboxes and
crawlers, not people, so the funnel ledger classifies an IP-only subject from
one of these networks as ``unknown`` (see app/services/hosting_networks.py).

This script rebuilds the CIDR snapshot from RIPEstat's public
``announced-prefixes`` endpoint (no key) for the ASNs in HOSTING_ASNS, collapses
overlapping prefixes, and writes one ``<cidr> <label>`` line per network.

Usage:
  python3 scripts/refresh_hosting_networks.py            # rewrite the file
  python3 scripts/refresh_hosting_networks.py --check    # exit 1 if it would change

Exit codes:
  0  written (or --check found no change)
  1  --check: the snapshot is stale
  2  fetch/parse failure (the existing file is left untouched)
"""

from __future__ import annotations

import argparse
import ipaddress
import json
import sys
import urllib.request
from datetime import UTC, datetime
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "config" / "hosting_networks.txt"
RIPE = "https://stat.ripe.net/data/announced-prefixes/data.json?resource=AS{asn}"

# Cloud / VPS providers whose address space is overwhelmingly machines, not
# people's home or office connections. Keep it to hosting-first ASNs: an ISP or
# a mixed enterprise ASN here would bury real humans in `unknown`.
HOSTING_ASNS: dict[int, str] = {
    14618: "AWS",
    16509: "AWS",
    8075: "Microsoft",
    396982: "GoogleCloud",
    15169: "Google",
    24940: "Hetzner",
    213230: "Hetzner",
    14061: "DigitalOcean",
    16276: "OVH",
    63949: "Akamai-Linode",
    31898: "Oracle",
    20473: "Vultr",
    51167: "Contabo",
    45102: "Alibaba",
}


def _fetch(asn: int) -> list[str]:
    with urllib.request.urlopen(RIPE.format(asn=asn), timeout=60) as resp:  # noqa: S310 — fixed https host
        data = json.load(resp)
    return [p["prefix"] for p in data["data"]["prefixes"]]


def build() -> str:
    by_label: dict[str, list] = {}
    for asn, label in HOSTING_ASNS.items():
        by_label.setdefault(label, []).extend(ipaddress.ip_network(p) for p in _fetch(asn))
    lines = []
    for label in sorted(by_label):
        nets = by_label[label]
        for version in (4, 6):
            for net in ipaddress.collapse_addresses(n for n in nets if n.version == version):
                lines.append(f"{net} {label}")
    header = (
        "# Generated by scripts/refresh_hosting_networks.py — do not edit by hand.\n"
        f"# Source: RIPEstat announced-prefixes, {datetime.now(UTC).date().isoformat()}.\n"
        f"# ASNs: {', '.join(f'AS{a}={n}' for a, n in HOSTING_ASNS.items())}\n"
    )
    return header + "\n".join(lines) + "\n"


def _body(text: str) -> list[str]:
    return [line for line in text.splitlines() if not line.startswith("#")]


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit 1 if the snapshot would change")
    args = ap.parse_args(argv)
    try:
        text = build()
    except Exception as exc:  # noqa: BLE001 — any fetch/parse failure keeps the old file
        print(f"refresh failed, file untouched: {exc}", file=sys.stderr)
        return 2
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        return 0 if _body(current) == _body(text) else 1
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {len(_body(text))} networks to {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
